### PR TITLE
Adjusting front end org chart

### PR DESCRIPTION
**Pull request by YHmaiti**

### CODE REVIEW

**Comment by YHmaiti** [comment]
This needs testing still. Perhaps as well small debugging.

I tried to run the server locally, yet faced some errors with bundle.js, please take a look, let me know if this is not on your end.

thank you both for the help, if any additional help is needed for this please let me know!

**Comment by NSel1727** [comment]
@AnishaRan The image process for getting the analytics image doesn't work on my end for whatever reason, but this is fine since it should still work on heroku. Based on this image Yohan sent me of the page, please pull and fix the css so the image is aligned better.
image

**Comment by AnishaRan** [comment]
Will do 👍🏽

**Comment by AnishaRan** [comment]
I am unable to see the image either but let's see if it works on heroku

**Comment by YHmaiti** [comment]
@AnishaRan if you think we should merge to main and see how it looks on Heroku, then sure, lemme commit some CSS but it still looks ugly and in the center. 

I think we shall figure out why it doesn't work on y'all guys end, it is quite weird, and we need y'all to be able to run it. @NSel1727

**Pull request merged**
